### ISSUE TITLE
Cannot read properties of null (reading 'classList')

### ISSUE THREAD

**Issue by tqkqt0** [attoae/quill-table-better#1]
Good job!

If I insert several tables in succession and the number of columns is different, an error occurs.

![image](https://github.com/attoae/quill-table-better/assets/29242704/e4a1f088-72ba-4465-9b67-b731173241ac)

```
ERROR
Cannot read properties of null (reading 'classList')
TypeError: Cannot read properties of null (reading 'classList')
at dt.handleMousedown (http://localhost:3000/static/js/bundle.js:167090:73)
at Ve.handleMousedown (http://localhost:3000/static/js/bundle.js:170111:30)
```

P.S
I want disable option for 'Table properties' and 'Cell properties'.
I would be happy if you could respond

thank you

**Comment by attoae** [comment]
Hi @tqkqt0
I have not reproduced this issue.
Are you attempting to insert a table within a table? Currently, this functionality is not supported.
Do you need to configure the operation bar?

**Comment by takato-tis** [comment]
Thank you for your reply. I really appreciate your excellent work.

> Are you attempting to insert a table within a table? Currently, this functionality is not supported.

Yes. For example, in the service I'm developing, users can freely add tables wherever they want. It would be helpful if we could prevent errors when adding a table within a table.

> Do you need to configure the operation bar?

Yes. In my service, including dark mode, I don't want the styling of table lines in published articles using Quill. It would be great if I could specify detailed editing options, or at the very least disable properties.

Other requests:
- I would be happy if I could add custom languages. (By the way, I want to use Japanese.)

**Comment by tqkqt0** [comment]
Thank you for your reply. I really appreciate your excellent work.

> Are you attempting to insert a table within a table? Currently, this functionality is not supported.

Yes. For example, in the service I'm developing, users can freely add tables wherever they want. It would be helpful if we could prevent errors when adding a table within a table.

> Do you need to configure the operation bar?

Yes. In my service, including dark mode, I don't want the styling of table lines in published articles using Quill. It would be great if I could specify detailed editing options, or at the very least disable properties.

Other requests:

- I would be happy if I could add custom languages. (By the way, I want to use Japanese.)

**Comment by attoae** [comment]
You can try v1.0.2 to configure the operation bar and add custom languages：[config](https://github.com/attoae/quill-table-better/tree/v1.0.2?tab=readme-ov-file#conifg)

**Comment by tqkqt0** [comment]
I tried it right away and it's perfect.
Thank you for your fast and great response.
