### ISSUE TITLE
[Bug] Adding a table in multiple editors

### ISSUE THREAD

**Issue by S1owe** [attoae/quill-table-better#18]
The problem is as follows, if you initialize several quill text editors, the table component will only work on the last editor. This is reproduced in the sandbox, I attach a screenshot
<img width="1603" alt="Снимок экрана 2024-09-05 в 16 09 48" src="https://github.com/user-attachments/assets/9bf7946c-ff1a-4885-b4b3-d970469a54bf">

**Comment by attoae** [comment]
Okay, I will fix it as soon as possible.

**Comment by sylvainpe** [comment]
I managed to fix the directional keys problem:

instead of :
`document.root.addEventListener('keyup', this.handleKeyup.bind(this));`

do:
`quill.root.addEventListener('keyup', this.handleKeyup.bind(this));`

For the first problem, I think ToolbarTable methods should not be static

**Comment by S1owe** [comment]
Thank you for the prompt solution of the problem!
