### ISSUE TITLE
[Request] Listening to the click event outside the button

### ISSUE THREAD

**Issue by S1owe** [attoae/quill-table-better#20]
It would be nice to add click tracking over time outside the table display button. So that when you click outside the button (the drop-down window for creating a table), the drop-down window closes. Now to close the window, you either need to click on the button or create a table

<img width="1523" alt="Снимок экрана 2024-09-06 в 14 13 42" src="https://github.com/user-attachments/assets/2ea7d412-d6d9-4055-b7e4-ab1c90d879b9">

**Comment by attoae** [comment]
Do you want only one dropdown window for creating tables to exist on the page ?

**Comment by S1owe** [comment]
Yes. I need one drop-down window. If you click on the create table button in the second editor, the first one should close. The same logic applies when clicking outside the table creation element

**Comment by S1owe** [comment]
I solved this problem as follows, I placed the following fragment in the registerToolbarTable method

document.addEventListener('click', (e: MouseEvent) => {
      const isClickOnBtn = e.composedPath().includes(button);
      if (isClickOnBtn) return;

      const tableEl = toolbar.container.querySelector('div.ql-table-select-container');
      if (!tableEl.classList.contains('ql-hidden')) this.tableSelect.hide(tableEl);
    });
    
<img width="706" alt="Снимок экрана 2024-09-06 в 14 46 23" src="https://github.com/user-attachments/assets/a0b304e0-7db5-456a-8157-bbf99805ba20">

**Comment by attoae** [comment]
Okay, I will handle this issue.
