### ISSUE TITLE
[BUG] Replacing default <p> tags by div make quill-table-better crash

### ISSUE THREAD

**Issue by sylvainpe** [attoae/quill-table-better#22]
Replacing default p tags by div make quill-table-better crash on load

```
const Block = Quill.import('blots/block');
Block.tagName = 'div';
Quill.register(Block);
```

How I load default data in editor:
```
const delta = quillEditor.clipboard.convert({
      html: defaultValue,
      text: '\n'
    });
    const range = quillEditor.selection.getRange();
    quillEditor.updateContents(delta, Quill.sources.USER);
    quillEditor.setSelection(delta.length() - range.length, Quill.sources.SILENT);
```

**Comment by attoae** [comment]
Why change the `tagName` of  `Block` ？
`Block` is the super class of `Quill`.
Maybe you want to change the `tagName` of  `TableCellBlock`, as follow：

```
const TableCellBlock = Quill.import('formats/table-cell-block');
TableCellBlock.tagName = 'div';
```

**Comment by attoae** [comment]
I'm not sure if changing it like this will cause other problems.
I'm wondering what is your starting point for doing this?

**Comment by sylvainpe** [comment]
I managed to keep using P as default. it's just that when i render my quill html I don't really like having paragraphs, because sometimes I just want to display things "in line".

I think you can close the issue if you like.

**Comment by attoae** [comment]
Okay, I need some time to verify this issue and get back to you later.

**Comment by attoae** [comment]
You can use the following method in the current version.
```
const Block = Quill.import('blots/block');
Block.tagName = 'div';
Quill.register({ 'blots/block': Block }, true);

Quill.register({
  'modules/table-better': QuillTableBetter
}, true);

const TableCellBlock = Quill.import('formats/table-cell-block');
TableCellBlock.tagName = 'div';
```
I will remove `TableCellBlock. tagName` in the next version and inherit the `Block.tagName`.
Change to the following：

```
const Block = Quill.import('blots/block');
Block.tagName = 'div';
Quill.register({ 'blots/block': Block }, true);

Quill.register({
  'modules/table-better': QuillTableBetter
}, true);
```
