### ISSUE TITLE
How to obtain data format

### ISSUE THREAD

**Issue by Libpzzz** [attoae/quill-table-better#25]
The data is so long, can it be converted into an object format? Or what method should I use to turn him into a whole object?
![image](https://github.com/user-attachments/assets/43c4cd93-6d6b-4c50-a11a-972b897cf36d)

**Comment by attoae** [comment]
`getContents` or `getSemanticHTML`?
[getSemanticHTML](https://quilljs.com/docs/api#getsemantichtml)

**Comment by Libpzzz** [comment]
> `getContents`或`getSemanticHTML`? [getSemanticHTML](https://quilljs.com/docs/api#getsemantichtml)

This is the result I obtained using getContents, but this data structure is a bit complex for me because I need to transmit it to the mobile end, but I cannot directly see the content in the table.
I have another question, How can I use quill-delta-to-html to convert a table to html。

**Comment by attoae** [comment]
> This is the result I obtained using getContents, but this data structure is a bit complex for me because I need to transmit it to the mobile end, but I cannot directly see the content in the table.

This is the underlying data structure of `quill` [(Delta)](https://quilljs.com/docs/delta).

> I have another question, How can I use quill-delta-to-html to convert a table to html。

You should look at the `quill-delta-to-html` documentation.

**Comment by Libpzzz** [comment]
> > 这是我使用getContents得到的结果，但是这个数据结构对我来说有点复杂，因为我需要传输到移动端，但是又不能直接看到表格里的内容。
> 
> `quill` [这是（Delta）](https://quilljs.com/docs/delta)的底层数据结构。
> 
> > 我还有一个问题，如何使用 quill-delta-to-html 将表格转换为 html。
> 
> 你应该看看`quill-delta-to-html`文档。

I read quill-delta-to-html recently submitted code is two years ago, the Internet did not find how to convert to table, so I want to understand the Delta table data structure to deal with themselves

**Comment by Libpzzz** [comment]
> > 这是我使用getContents得到的结果，但是这个数据结构对我来说有点复杂，因为我需要传输到移动端，但是又不能直接看到表格里的内容。
> 
> `quill` [这是（Delta）](https://quilljs.com/docs/delta)的底层数据结构。
> 
> > 我还有一个问题，如何使用 quill-delta-to-html 将表格转换为 html。
> 
> 你应该看看`quill-delta-to-html`文档。

https://github.com/attoae/quill-table-better/issues/25#issuecomment-2349336001
