### ISSUE TITLE
Splitting Cells Works for Only Two Rows

### ISSUE THREAD

**Issue by dustinormond** [attoae/quill-table-better#26]
When I split a cell that is merged across two rows, it works great; however, when I split a cell that is merged across three or more rows, it shifts all but the first two rows to the left one cell:

Original (dots are merged with columns a, b, and c respectively:
```
a  b  c  1  2  3
.  .  .  4  5  6
.  .  .  7  8  9
```
New format after splitting column c (underscore represents an empty cell):
```
a  b  c  1  2  3
.  .  _  4  5  6
.  .  7  8  9  _
```
This is what it should look like instead:
```
a  b  c  1  2  3
.  .  _  4  5  6
.  .  _  7  8  9 
```

**Comment by attoae** [comment]
Okay, I will handle this issue.

**Comment by dustinormond** [comment]
That was fast! Thank you!
