### ISSUE TITLE
quill-table-better The data format used for output cannot be displayed inside rich text

### ISSUE THREAD

**Issue by Libpzzz** [attoae/quill-table-better#27]
![image](https://github.com/user-attachments/assets/2e93fba0-8010-47f5-8c7f-6cb3126b7269)
After this use, there is no normal insertion table content
![image](https://github.com/user-attachments/assets/44c6edd6-ee11-46e7-94e9-f77c2d6f3287)

**Comment by attoae** [comment]
#12
