### ISSUE TITLE
How to disable editor buttons in the toolbar when the table cell is active?

### ISSUE THREAD

**Issue by Alpscloud** [attoae/quill-table-better#33]
Hello! Can you help me with my problem: I see that when focusing on a table cell, some editor control buttons are blocked. How can I specify which buttons to block and which not? For example, I need to prohibit adding headings, images, etc.
![photo_2024-10-08_16-34-01](https://github.com/user-attachments/assets/993a639d-5fa7-440c-b6d8-ba6af81d8a5e)

The part of my editor component code where I include this plugin:
`const postsDesignOptions = {
  theme: 'snow',
  modules: {
    htmlEditButton: {},
    toolbar: {
      container: toolbarOptions.postsDesign,
    },
    'table-better': {
      menus: ['column', 'row', 'merge', 'table', 'cell', 'wrap', 'delete'],
      toolbarTable: true,
    },
    keyboard: {
      bindings: QuillTableBetter.keyboardBindings,
    },
  },
};
`

**Comment by attoae** [comment]
The current version does not support specifying to disable buttons.
Do you want to specify disable buttons in future versions?

**Comment by attoae** [comment]
Refer to [toolbarbuttons](https://github.com/attoae/quill-table-better?tab=readme-ov-file#toolbarbuttons) and [Formats supported by table](https://github.com/attoae/quill-table-better?tab=readme-ov-file#formats-supported-by-table).
