### ISSUE TITLE
Add german language support

### ISSUE THREAD

**Issue by cbc-technology** [attoae/quill-table-better#38]
Thanks for your work so far. For a project i needed a german and english version. Attached you find my translations (de_DE):

`'col': 'Spalte',
'insColL': 'Spalte links einfügen',
'insColR': 'Spalte rechts einfügen',
'delCol': 'Spalte löschen',
'row': 'Zeile',
'insRowAbv': 'Zeile oberhalb einfügen',
'insRowBlw': 'Zeile unterhalb einfügen',
'delRow': 'Zeile löschen',
'mCells': 'Zellen verbinden',
'sCell': 'Zelle teilen',
'tblProps': 'Tabelleneingenschaften',
'cellProps': 'Zelleneigenschaften',
'insParaOTbl': 'Absatz außerhalb der Tabelle einfügen',
'insB4': 'Davor einfügen',
'insAft': 'Danach einfügen',
'delTable': 'Tabelle löschen',
'border': 'Rahmen',
'color': 'Farbe',
'width': 'Breite',
'background': 'Schattierung',
'dims': 'Maße',
'height': 'Höhe',
'padding': 'Abstand',
'tblCellTxtAlm': 'Ausrichtung',
'alCellTxtL': 'Zellentext links ausrichten',
'alCellTxtC': 'Zellentext mittig ausrichten',
'alCellTxtR': 'Zellentext rechts ausrichten',
'jusfCellTxt': 'Zellentext Blocksatz',
'alCellTxtT': 'Zellentext oben ausrichten',
'alCellTxtM': 'Zellentext mittig ausrichten',
'alCellTxtB': 'Zellentext unten ausrichten',
'dimsAlm': 'Maße und Ausrichtung',
'alTblL': 'Tabelle links ausrichten',
'tblC': 'Tabelle mittig ausrichten',
'alTblR': 'Tabelle rechts ausrichten',
'save': 'Speichern',
'cancel': 'Abbrechen',
'colorMsg': 'Die Farbe ist ungültig. Probiere "#FF0000", "rgb(255,0,0)" oder "red".',
'dimsMsg': 'Der Wert ist ungültig. Probiere "10px", "2em" oder einfach "2".',
'colorPicker': 'Farbwähler',
'removeColor': 'Farbe entfernen',
'black': 'Schwarz',
'dimGrey': 'Dunkelgrau',
'grey': 'Grau',
'lightGrey': 'Hellgrau',
'white': 'Weiß',
'red': 'Rot',
'orange': 'Orange',
'yellow': 'Gelb',
'lightGreen': 'Hellgrün',
'green': 'Grün',
'aquamarine': 'Aquamarin',
'turquoise': 'Türkis',
'lightBlue': 'Hellblau',
'blue': 'Blau',
'purple': 'Lila'`

**Comment by attoae** [comment]
ok
