### ISSUE TITLE
Feature Request with Del Key

### ISSUE THREAD

**Issue by dustinormond** [attoae/quill-table-better#42]
I have a couple suggestions:

1. Is it possible to have the selected cells delete the contents on the Del key? For example, if I hit the delete key when selecting two cells (see image below), can you delete both the a and b:
![image](https://github.com/user-attachments/assets/a078b778-1526-49ca-92b2-849a6914a59b)
2. Is it possible to have the selected cells be removed on the Backspace key? For example, if I hit the backspace key when selecting two cells (see image above), can you delete the column (or row) assuming all cells in the row or column are selected when the backspace key is hit?

**Comment by attoae** [comment]
Delete an entire row or column when all cells in the row or column are selected?
Requires a key combination, for example `Ctrl + Backspace` or `Ctrl + Delete`. Just `Backspace` can be confusing.

**Comment by dustinormond** [comment]
Sounds great! Does this already work? I just tested it and it doesn't appear so.
