### ISSUE TITLE
Create a bullet list in the table destroys it and adding a new bullet point doesn't work  

### ISSUE THREAD

**Issue by robertSt7** [attoae/quill-table-better#47]
First thanks for the great plugin.

I am facing the following problem:
When creating a bullet list in a cell and then try to import the data after exporting, a TypeError occurs: 
`Uncaught TypeError: Cannot convert undefined or null to object`

Also adding a new bullet point doesn't work.

**Comment by attoae** [comment]
Refer to #12.
`setContents` causes the table to not display properly, replace with `updateContents`.
The [Pull request](https://github.com/slab/quill/pull/4398) needs to be merged to resolve the `setContents` issue.

**Comment by robertSt7** [comment]
@attoae I am using `updateContents` and the table is displayed after re-importing, but with smaller row size or some cells are deleted. 
There are also some problems during editing like: 
When adding some points and then delete one with backspace a new cell will be added
![image](https://github.com/user-attachments/assets/837c9799-e07c-4ad0-81eb-7fc99585db6a)

**Comment by attoae** [comment]
Okay, I will handle this issue.
