### ISSUE TITLE
Change column width doesn't work, when there are merged cells

### ISSUE THREAD

**Issue by robertSt7** [attoae/quill-table-better#48]
Change column width doesn't work, when there are merged cells in the same column.

![image](https://github.com/user-attachments/assets/0fe57427-c761-42cc-89a9-93ac9b3b2c2f)

The column width of the blue cell isn't changeable, because there are merged cells in the row before.

**Comment by attoae** [comment]
`.ql-editor table {
    table-layout: fixed;
    width: 100%;
}`
`width: unset;`  cover `width: 100%;`

**Comment by robertSt7** [comment]
@attoae Thanks a lot this solves my issue
