### ISSUE TITLE
[Request] Quill-table-better support with ngx-quill

### ISSUE THREAD

**Issue by kupadhyay** [attoae/quill-table-better#55]
Hello Attoae,

Thanks for creating fully working table module with Quill, In our project we are using ngx-quill package with Angular.
quill-table-better is working with ngx-quill ?, i tried to register quill-table-better but getting below error
![image](https://github.com/user-attachments/assets/337549b3-51d7-4ecf-b55b-f9b6263e089e)

Please refer below stackblitz for reference purpose
https://stackblitz.com/edit/finitelooper-ng16-1uydiu89?file=package.json,src%2Findex.html,src%2Fapp%2Fapp.module.ts,src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts

If i missed any further configuration please let me know.

**Comment by attoae** [comment]
It can be used normally.
<img src="https://github.com/user-attachments/assets/e43fe778-82c1-48d5-ad45-70ecd1ae3d86" />

**Comment by kishan110** [comment]
Correct it's working normally, but in our project we have used ngx-quill extensively with some custom changes. so want to integrate **QuillTableBetter** with it.
With <Quill-editor> only getting this register error. could you please help for the same.
<img width="736" alt="image" src="https://github.com/user-attachments/assets/33799c8a-a3dd-4ee7-9ecb-a051dbf413f9">

**Comment by attoae** [comment]
<img src="https://github.com/user-attachments/assets/1a357a84-4ee2-44dc-9995-792c9fb65da3" />
<img src="https://github.com/user-attachments/assets/a446fdac-b30e-4122-9543-deb7e2762525" />

**Comment by kupadhyay** [comment]
Thanks @attoae for quick support.
