### ISSUE TITLE
Table is not showing

### ISSUE THREAD

**Issue by hsab1997** [attoae/quill-table-better#6]
i am using this in the react project, table is not showing in the text editor when I am inspecting it shows the p tags
[table.webm](https://github.com/user-attachments/assets/8033e3ef-1ba7-4da6-a4be-d0efd09714fe)

**Comment by attoae** [comment]
You can take a look at this issue [(react-quill)](https://github.com/zenoamaro/react-quill/issues/979).
This library does not yet support Quill 2.0 version.

**Comment by srikanth-5** [comment]
even i am getting the same issue though i have installed the react-quill-new , the table is being copied perfectly from other source but im not able to create a table in the editor , all im getting is <p> tags

**Comment by attoae** [comment]
@srikanth-5 
Hi, you can take a look at this demo.
[quill-table-better Codepen Demo(React)](https://codesandbox.io/p/sandbox/react-quill-wcfghd)
